name: C/C++ Make Using Build Script

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Libs
      run: sudo apt-get install -y libsfml-dev libglm-dev libglew-dev
    - name: Bulid Production Release
      run: ./build.sh buildprod Production
